const HTTPStatus = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

const SECOND_TO_MILLISECOND = {
  ONE: 1000,
  FIVE: 5000,
  TEN: 10000,
  THIRTY: 30000,
}

const MINUTE_TO_SECOND = {
  ONE: 60,
  FIVE: 5 * 60,
  TEN: 10 * 60,
  THIRTY: 30 * 60,
}

const MINUTE_TO_MILLISECOND = {
  ONE: MINUTE_TO_SECOND.ONE * SECOND_TO_MILLISECOND.ONE,
  FIVE: MINUTE_TO_SECOND.FIVE * SECOND_TO_MILLISECOND.ONE,
  TEN: MINUTE_TO_SECOND.TEN * SECOND_TO_MILLISECOND.ONE,
  THIRTY: MINUTE_TO_SECOND.THIRTY * SECOND_TO_MILLISECOND.ONE,
}

module.exports = {
  HTTPStatus,
  SECOND_TO_MILLISECOND,
  MINUTE_TO_SECOND,
  MINUTE_TO_MILLISECOND,
}